use std::{
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use dashmap::DashMap;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

use crate::{
    app::AppContext,
    commands::sync::{SyncRunOptions, SyncSummary},
    parsers::{SyncEvent, SyncSummaryEvent},
    store::{HolderKind, Store},
};

/// In-process identifier for one usage import job.
pub type JobId = String;

pub use crate::parsers::SyncEvent as JobEvent;

/// Pollable lifecycle status for usage import jobs.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    /// The job is present in the registry and considered running.
    Running,
    /// The job finished successfully.
    Completed,
    /// The job failed.
    Failed,
    /// Cancellation was requested.
    Cancelled,
}

/// Stable snapshot returned to adapters that poll a job.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct JobSnapshot {
    /// Job id generated by [`JobRegistry::start`].
    pub job_id: JobId,
    /// Current lifecycle state.
    pub status: JobStatus,
    /// Last human-readable summary, when available.
    pub summary: Option<String>,
    /// Last observed sync event.
    pub last_event: Option<SyncEvent>,
    /// Error detail for failed jobs.
    pub error: Option<String>,
    /// RFC 3339 start timestamp.
    pub started_at: String,
    /// RFC 3339 finish timestamp for terminal states.
    pub finished_at: Option<String>,
}

#[derive(Debug)]
struct JobState {
    snapshot: JobSnapshot,
    cancel: CancellationToken,
}

/// In-memory bridge from future sync progress push events to pollable snapshots.
#[derive(Debug, Clone, Default)]
pub struct JobRegistry {
    inner: Arc<DashMap<JobId, Arc<Mutex<JobState>>>>,
}

/// Options accepted by the usage import job starter.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct SyncOptions {
    /// Rebuild local usage tables before importing.
    pub rebuild: bool,
    /// Restrict import to recent days. M0- stores the option only.
    pub recent_days: Option<u32>,
    /// Restrict import to one source string.
    pub source: Option<String>,
    /// Optional parser concurrency override. Values below 1 are ignored by the
    /// sync runner; callers can use this to throttle library/API imports.
    pub parallelism: Option<usize>,
}

impl JobRegistry {
    /// Starts a real in-process sync task and returns its id plus a progress receiver.
    pub fn start(&self, store: &Store, options: SyncOptions) -> (JobId, mpsc::Receiver<JobEvent>) {
        let job_id = new_job_id();
        let (tx, rx) = mpsc::channel(128);
        let now = crate::util::now_utc();
        let cancel = CancellationToken::new();
        let state = JobState {
            snapshot: JobSnapshot {
                job_id: job_id.clone(),
                status: JobStatus::Running,
                summary: None,
                last_event: None,
                error: None,
                started_at: now,
                finished_at: None,
            },
            cancel: cancel.clone(),
        };
        let state = Arc::new(Mutex::new(state));
        self.inner.insert(job_id.clone(), Arc::clone(&state));

        let store = store.clone();
        let options = options.clone();
        let job_id_for_task = job_id.clone();
        tokio::spawn(async move {
            run_job(job_id_for_task, store, options, cancel, tx, state).await;
        });
        (job_id, rx)
    }

    /// Returns a cloned job snapshot without holding the mutex across caller work.
    pub fn snapshot(&self, id: &str) -> Option<JobSnapshot> {
        self.inner
            .get(id)
            .and_then(|entry| entry.lock().ok().map(|state| state.snapshot.clone()))
    }

    /// Requests cancellation for a registered job.
    pub fn cancel(&self, id: &str) -> bool {
        let Some(entry) = self.inner.get(id) else {
            return false;
        };
        let Ok(mut state) = entry.lock() else {
            return false;
        };
        state.cancel.cancel();
        state.snapshot.status = JobStatus::Cancelled;
        state.snapshot.finished_at = Some(crate::util::now_utc());
        true
    }

    /// Returns recent snapshots. Terminal jobs beyond `limit` may be evicted;
    /// running jobs are always retained.
    pub fn list_recent(&self, limit: usize) -> Vec<JobSnapshot> {
        let mut snapshots = self
            .inner
            .iter()
            .filter_map(|entry| entry.lock().ok().map(|state| state.snapshot.clone()))
            .collect::<Vec<_>>();
        snapshots.sort_by(|a, b| {
            b.started_at
                .cmp(&a.started_at)
                .then(b.job_id.cmp(&a.job_id))
        });
        if limit > 0 {
            let terminal_ids = snapshots
                .iter()
                .filter(|snapshot| {
                    snapshot.status != JobStatus::Running
                        && snapshots
                            .iter()
                            .filter(|item| item.status != JobStatus::Running)
                            .position(|item| item.job_id == snapshot.job_id)
                            .is_some_and(|index| index >= limit)
                })
                .map(|snapshot| snapshot.job_id.clone())
                .collect::<Vec<_>>();
            for id in terminal_ids {
                self.inner.remove(&id);
            }
            snapshots.retain(|snapshot| self.inner.contains_key(&snapshot.job_id));
        }
        snapshots
    }
}

async fn run_job(
    job_id: JobId,
    store: Store,
    options: SyncOptions,
    cancel: CancellationToken,
    outbound: mpsc::Sender<JobEvent>,
    state: Arc<Mutex<JobState>>,
) {
    let sync_options = SyncRunOptions {
        rebuild: options.rebuild,
        source: options
            .source
            .as_deref()
            .and_then(crate::models::SourceKind::parse_id),
        recent_days: options.recent_days,
        parallelism: options.parallelism,
        json_events: false,
    };
    let app = AppContext {
        paths: store.paths.clone(),
        current_exe: std::env::current_exe().unwrap_or_default(),
    };
    let (mut internal_tx, mut internal_rx) = mpsc::channel(128);
    let state_for_events = Arc::clone(&state);
    let event_forwarder = tokio::spawn(async move {
        while let Some(event) = internal_rx.recv().await {
            update_state_from_event(&state_for_events, &event);
            let _ = outbound.send(event).await;
        }
    });

    let _ = internal_tx
        .send(SyncEvent::Started {
            job_id: job_id.clone(),
            files_total: 0,
        })
        .await;
    let _ = internal_tx
        .send(SyncEvent::LockWaiting { timeout_ms: 30_000 })
        .await;
    let lock_started = Instant::now();
    let result = match store.acquire_worker_lock_with(Duration::from_secs(30), HolderKind::Library)
    {
        Ok(lock) => {
            let lock_wait_ms = lock_started.elapsed().as_millis().min(u64::MAX as u128) as u64;
            let _ = internal_tx
                .send(SyncEvent::LockAcquired {
                    wait_ms: lock_wait_ms,
                })
                .await;
            let result = crate::commands::sync::run_once_with_cancel(
                &app,
                &store,
                lock_wait_ms,
                &sync_options,
                Some(&mut internal_tx),
                &cancel,
            )
            .await;
            drop(lock);
            result
        }
        Err(err) => Err(anyhow::Error::new(err)),
    };
    match result {
        Ok(summary) if cancel.is_cancelled() => {
            let _ = internal_tx.send(SyncEvent::Cancelled).await;
            finish_state(
                &state,
                JobStatus::Cancelled,
                Some(summary_text(&summary)),
                None,
            );
        }
        Ok(summary) => {
            let event = SyncEvent::Finished {
                summary: SyncSummaryEvent {
                    sources: summary.sources.len(),
                    total_seen: summary.total_seen,
                    total_inserted: summary.total_inserted,
                },
            };
            let _ = internal_tx.send(event).await;
            finish_state(
                &state,
                JobStatus::Completed,
                Some(summary_text(&summary)),
                None,
            );
        }
        Err(err) => {
            let message = err.to_string();
            let _ = internal_tx
                .send(SyncEvent::Failed {
                    error: message.clone(),
                })
                .await;
            finish_state(&state, JobStatus::Failed, None, Some(message));
        }
    }
    drop(internal_tx);
    let _ = event_forwarder.await;
}

fn update_state_from_event(state: &Arc<Mutex<JobState>>, event: &SyncEvent) {
    if let Ok(mut state) = state.lock() {
        state.snapshot.last_event = Some(event.clone());
    }
}

fn finish_state(
    state: &Arc<Mutex<JobState>>,
    status: JobStatus,
    summary: Option<String>,
    error: Option<String>,
) {
    if let Ok(mut state) = state.lock() {
        state.snapshot.status = status;
        state.snapshot.summary = summary;
        state.snapshot.error = error;
        state.snapshot.finished_at = Some(crate::util::now_utc());
    }
}

fn summary_text(summary: &SyncSummary) -> String {
    format!(
        "sources={} seen={} inserted={}",
        summary.sources.len(),
        summary.total_seen,
        summary.total_inserted
    )
}

fn new_job_id() -> JobId {
    static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);
    let sequence = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    format!("job-{sequence}")
}

#[allow(dead_code)]
fn _keep_sync_summary_public_contract(_: Option<SyncSummary>) {}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::paths::AppPaths;
    use tempfile::TempDir;

    #[tokio::test]
    async fn start_returns_running_snapshot() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let paths = AppPaths::with_root(temp.path().to_path_buf())?;
        let store = Store::new(&paths)?;
        let registry = JobRegistry::default();

        let (job_id, rx) = registry.start(&store, SyncOptions::default());
        let snapshot = registry
            .snapshot(&job_id)
            .expect("job snapshot should exist");

        assert_eq!(snapshot.job_id, job_id);
        assert_eq!(snapshot.status, JobStatus::Running);
        drop(rx);
        Ok(())
    }

    #[test]
    fn sync_options_accepts_parallelism_without_breaking_source_json() -> anyhow::Result<()> {
        let options: SyncOptions = serde_json::from_str(
            r#"{"source":"codex","recent_days":7,"parallelism":2,"rebuild":false}"#,
        )?;
        assert_eq!(options.source.as_deref(), Some("codex"));
        assert_eq!(options.recent_days, Some(7));
        assert_eq!(options.parallelism, Some(2));

        let payload = serde_json::to_value(&options)?;
        assert_eq!(payload["source"], "codex");
        assert_eq!(payload["parallelism"], 2);
        Ok(())
    }
}
