use std::{
    collections::VecDeque,
    error::Error,
    fmt,
    sync::{Arc, Mutex},
    time::{Duration, Instant},
};

use dashmap::DashMap;
use serde::{Deserialize, Serialize};
use tokio::sync::mpsc;
use tokio_util::sync::CancellationToken;

use crate::{
    app::AppContext,
    parsers::{SyncEvent, SyncSummaryEvent},
    store::{HolderKind, Store},
    sync::types::{SyncRunOptions, SyncSummary},
};

/// In-process identifier for one usage import job.
pub type JobId = String;

pub use crate::parsers::SyncEvent as JobEvent;

/// Pollable lifecycle status for usage import jobs.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    /// The job is present in the registry and considered running.
    Running,
    /// Cancellation has been requested and the worker is unwinding.
    Cancelling,
    /// The job finished successfully.
    Completed,
    /// The job failed.
    Failed,
    /// Cancellation was requested.
    Cancelled,
}

impl JobStatus {
    fn is_active(self) -> bool {
        matches!(self, Self::Running | Self::Cancelling)
    }
}

/// Stable snapshot returned to adapters that poll a job.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct JobSnapshot {
    /// Job id generated by [`JobRegistry::start`].
    pub job_id: JobId,
    /// Current lifecycle state.
    pub status: JobStatus,
    /// Last human-readable summary, when available.
    pub summary: Option<String>,
    /// Last observed sync event.
    pub last_event: Option<SyncEvent>,
    /// Error detail for failed jobs.
    pub error: Option<String>,
    /// RFC 3339 start timestamp.
    pub started_at: String,
    /// RFC 3339 finish timestamp for terminal states.
    pub finished_at: Option<String>,
}

#[derive(Debug)]
struct JobState {
    snapshot: JobSnapshot,
    cancel: CancellationToken,
}

/// Maximum number of terminal (Completed/Failed/Cancelled) jobs retained in
/// memory. Active and cancelling jobs are never evicted.
const MAX_TERMINAL_JOBS: usize = 100;

/// In-memory bridge from future sync progress push events to pollable snapshots.
#[derive(Clone)]
pub struct JobRegistry {
    inner: Arc<DashMap<JobId, Arc<Mutex<JobState>>>>,
    admission: Arc<Mutex<()>>,
    terminal_hooks: TerminalHooks,
    /// Insertion-ordered deque of terminal job ids, capped at `MAX_TERMINAL_JOBS`.
    terminal_order: Arc<Mutex<VecDeque<JobId>>>,
    /// Executes the actual sync work. Injected by the adapter layer (CLI/web)
    /// so this module does not import `commands::sync` (ARCH-002).
    executor: Arc<dyn crate::sync::executor::SyncExecutor>,
}

impl fmt::Debug for JobRegistry {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("JobRegistry")
            .field("jobs", &self.inner.len())
            .finish()
    }
}

impl Default for JobRegistry {
    fn default() -> Self {
        Self::new(Arc::new(crate::commands::sync::CommandSyncExecutor))
    }
}

impl JobRegistry {
    /// Creates a `JobRegistry` with a caller-provided executor.
    ///
    /// Use [`Default::default`] in production (injects `CommandSyncExecutor`);
    /// pass a stub in tests.
    pub fn new(executor: Arc<dyn crate::sync::executor::SyncExecutor>) -> Self {
        Self {
            inner: Arc::default(),
            admission: Arc::default(),
            terminal_hooks: TerminalHooks::default(),
            terminal_order: Arc::default(),
            executor,
        }
    }
}

/// Callback list fired once after a job reaches a terminal state.
///
/// The web layer registers cache-invalidation hooks here; hooks must be
/// cheap and non-blocking because they run inside the job task.
type TerminalHook = Arc<dyn Fn() + Send + Sync>;

#[derive(Clone, Default)]
struct TerminalHooks(Arc<Mutex<Vec<TerminalHook>>>);

impl fmt::Debug for TerminalHooks {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let count = self.0.lock().map(|hooks| hooks.len()).unwrap_or(0);
        f.debug_struct("TerminalHooks")
            .field("count", &count)
            .finish()
    }
}

impl TerminalHooks {
    fn fire(&self) {
        let hooks = self.0.lock().map(|hooks| hooks.clone()).unwrap_or_default();
        for hook in hooks {
            hook();
        }
    }
}

/// Error returned when the in-process sync job admission policy rejects a start
/// request instead of spawning another waiter.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct JobStartRejected {
    /// Currently active job that owns the single in-process sync slot.
    pub active_job_id: JobId,
}

impl fmt::Display for JobStartRejected {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "sync job already active: {}",
            self.active_job_id.as_str()
        )
    }
}

impl Error for JobStartRejected {}

/// Options accepted by the usage import job starter.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub struct SyncOptions {
    /// Rebuild local usage tables before importing.
    pub rebuild: bool,
    /// Restrict import to recent days. M0- stores the option only.
    pub recent_days: Option<u32>,
    /// Restrict import to one source string.
    pub source: Option<String>,
    /// Optional parser concurrency override. Values below 1 are ignored by the
    /// sync runner; callers can use this to throttle library/API imports.
    pub parallelism: Option<usize>,
}

impl JobRegistry {
    /// Starts a real in-process sync task when the in-process admission slot is
    /// available and returns its id plus a progress receiver.
    pub fn try_start(
        &self,
        store: &Store,
        options: SyncOptions,
    ) -> Result<(JobId, mpsc::Receiver<JobEvent>), JobStartRejected> {
        let _admission = self
            .admission
            .lock()
            .expect("job registry admission mutex poisoned");
        if let Some(active) = self.active_job_id() {
            return Err(JobStartRejected {
                active_job_id: active,
            });
        }

        Ok(self.spawn_start(store, options))
    }

    /// Starts a real in-process sync task and returns its id plus a progress
    /// receiver. If the registry is already running/cancelling one job, this
    /// compatibility wrapper returns a terminal failed snapshot instead of
    /// spawning another lock waiter.
    pub fn start(&self, store: &Store, options: SyncOptions) -> (JobId, mpsc::Receiver<JobEvent>) {
        match self.try_start(store, options) {
            Ok(started) => started,
            Err(rejected) => self.insert_rejected_snapshot(rejected),
        }
    }

    /// Registers a callback fired once after any job reaches a terminal state
    /// (Completed / Failed / Cancelled). Used by the web layer to invalidate
    /// read-side caches that depend on freshly synced data.
    pub fn register_terminal_hook(&self, hook: impl Fn() + Send + Sync + 'static) {
        self.terminal_hooks
            .0
            .lock()
            .expect("job registry terminal hooks mutex poisoned")
            .push(Arc::new(hook));
    }

    fn spawn_start(
        &self,
        store: &Store,
        options: SyncOptions,
    ) -> (JobId, mpsc::Receiver<JobEvent>) {
        let job_id = new_job_id();
        let (tx, rx) = mpsc::channel(128);
        let now = crate::util::now_utc();
        let cancel = CancellationToken::new();
        let state = JobState {
            snapshot: JobSnapshot {
                job_id: job_id.clone(),
                status: JobStatus::Running,
                summary: None,
                last_event: None,
                error: None,
                started_at: now,
                finished_at: None,
            },
            cancel: cancel.clone(),
        };
        let state = Arc::new(Mutex::new(state));
        self.inner.insert(job_id.clone(), Arc::clone(&state));

        let store = store.clone();
        let options = options.clone();
        let job_id_for_task = job_id.clone();
        let ctx = JobContext {
            hooks: self.terminal_hooks.clone(),
            jobs: Arc::clone(&self.inner),
            order: Arc::clone(&self.terminal_order),
            executor: Arc::clone(&self.executor),
        };
        tokio::spawn(async move {
            run_job(job_id_for_task, store, options, cancel, tx, state, ctx).await;
        });
        (job_id, rx)
    }

    fn insert_rejected_snapshot(
        &self,
        rejected: JobStartRejected,
    ) -> (JobId, mpsc::Receiver<JobEvent>) {
        let job_id = new_job_id();
        let (_tx, rx) = mpsc::channel(1);
        let now = crate::util::now_utc();
        let message = rejected.to_string();
        let state = JobState {
            snapshot: JobSnapshot {
                job_id: job_id.clone(),
                status: JobStatus::Failed,
                summary: Some("sync job start rejected by admission policy".to_string()),
                last_event: None,
                error: Some(message),
                started_at: now.clone(),
                finished_at: Some(now),
            },
            cancel: CancellationToken::new(),
        };
        self.inner
            .insert(job_id.clone(), Arc::new(Mutex::new(state)));
        note_terminal_job(&job_id, &self.inner, &self.terminal_order);
        (job_id, rx)
    }

    /// Returns a cloned job snapshot without holding the mutex across caller work.
    pub fn snapshot(&self, id: &str) -> Option<JobSnapshot> {
        self.inner
            .get(id)
            .and_then(|entry| entry.lock().ok().map(|state| state.snapshot.clone()))
    }

    /// Requests cancellation for a registered job.
    pub fn cancel(&self, id: &str) -> bool {
        let Some(entry) = self.inner.get(id) else {
            return false;
        };
        let Ok(mut state) = entry.lock() else {
            return false;
        };
        state.cancel.cancel();
        if state.snapshot.status == JobStatus::Running {
            state.snapshot.status = JobStatus::Cancelling;
            state.snapshot.summary = Some("cancellation requested".to_string());
            state.snapshot.finished_at = None;
        }
        true
    }

    /// Returns recent snapshots sorted newest-first.
    /// Terminal jobs are evicted eagerly on completion; this method is read-only.
    pub fn list_recent(&self, limit: usize) -> Vec<JobSnapshot> {
        let mut snapshots = self
            .inner
            .iter()
            .filter_map(|entry| entry.lock().ok().map(|state| state.snapshot.clone()))
            .collect::<Vec<_>>();
        snapshots.sort_by(|a, b| {
            b.started_at
                .cmp(&a.started_at)
                .then(b.job_id.cmp(&a.job_id))
        });
        if limit > 0 && snapshots.len() > limit {
            snapshots.truncate(limit);
        }
        snapshots
    }

    fn active_job_id(&self) -> Option<JobId> {
        self.inner.iter().find_map(|entry| {
            let state = entry.lock().ok()?;
            state
                .snapshot
                .status
                .is_active()
                .then(|| state.snapshot.job_id.clone())
        })
    }
}

/// Per-job context: retirement handles and the executor that does the sync work.
#[derive(Clone)]
struct JobContext {
    hooks: TerminalHooks,
    jobs: Arc<DashMap<JobId, Arc<Mutex<JobState>>>>,
    order: Arc<Mutex<VecDeque<JobId>>>,
    executor: Arc<dyn crate::sync::executor::SyncExecutor>,
}

impl JobContext {
    /// Fires terminal hooks, then evicts the oldest terminal jobs beyond
    /// [`MAX_TERMINAL_JOBS`].
    fn retire(&self, job_id: &JobId) {
        note_terminal_job(job_id, &self.jobs, &self.order);
        self.hooks.fire();
    }
}

async fn run_job(
    job_id: JobId,
    store: Store,
    options: SyncOptions,
    cancel: CancellationToken,
    outbound: mpsc::Sender<JobEvent>,
    state: Arc<Mutex<JobState>>,
    ctx: JobContext,
) {
    let sync_options = SyncRunOptions {
        rebuild: options.rebuild,
        source: options
            .source
            .as_deref()
            .and_then(crate::models::SourceKind::parse_id),
        recent_days: options.recent_days,
        parallelism: options.parallelism,
        provider_map: None,
        json_events: false,
        allow_lossy_rebuild: false,
    };
    let app = AppContext {
        paths: store.paths.clone(),
        current_exe: std::env::current_exe().unwrap_or_default(),
    };
    let (mut internal_tx, mut internal_rx) = mpsc::channel(128);
    let state_for_events = Arc::clone(&state);
    let event_forwarder = tokio::spawn(async move {
        while let Some(event) = internal_rx.recv().await {
            update_state_from_event(&state_for_events, &event);
            let _ = outbound.send(event).await;
        }
    });

    let _ = internal_tx
        .send(SyncEvent::Started {
            job_id: job_id.clone(),
            files_total: 0,
        })
        .await;
    let _ = internal_tx
        .send(SyncEvent::LockWaiting { timeout_ms: 30_000 })
        .await;
    let lock_started = Instant::now();
    let result = match acquire_worker_lock_for_job(&store, Duration::from_secs(30), &cancel).await {
        Ok(Some(lock)) => {
            let fenced_store = lock.fenced_store();
            let heartbeat = lock.start_default_heartbeat();
            let lock_wait_ms = lock_started.elapsed().as_millis().min(u64::MAX as u128) as u64;
            let _ = internal_tx
                .send(SyncEvent::LockAcquired {
                    wait_ms: lock_wait_ms,
                })
                .await;
            let result = match fenced_store.bootstrap() {
                Ok(()) => {
                    ctx.executor
                        .run_once(
                            &app,
                            &fenced_store,
                            lock_wait_ms,
                            &sync_options,
                            Some(&mut internal_tx),
                            &cancel,
                        )
                        .await
                }
                Err(err) => Err(anyhow::Error::new(err)),
            };
            drop(heartbeat);
            drop(lock);
            result
        }
        Ok(None) => {
            let _ = internal_tx.send(SyncEvent::Cancelled).await;
            finish_state(
                &state,
                JobStatus::Cancelled,
                Some("cancellation requested".to_string()),
                None,
            );
            ctx.retire(&job_id);
            drop(internal_tx);
            let _ = event_forwarder.await;
            return;
        }
        Err(err) => Err(anyhow::Error::new(err)),
    };
    match result {
        Ok(summary) if cancel.is_cancelled() => {
            let _ = internal_tx.send(SyncEvent::Cancelled).await;
            finish_state(
                &state,
                JobStatus::Cancelled,
                Some(summary_text(&summary)),
                None,
            );
        }
        Ok(summary) => {
            let event = SyncEvent::Finished {
                summary: SyncSummaryEvent {
                    sources: summary.sources.len(),
                    total_seen: summary.total_seen,
                    total_inserted: summary.total_inserted,
                    stored_events: summary.stored_events,
                },
            };
            let _ = internal_tx.send(event).await;
            finish_state(
                &state,
                JobStatus::Completed,
                Some(summary_text(&summary)),
                None,
            );
        }
        Err(err) => {
            let message = err.to_string();
            let _ = internal_tx
                .send(SyncEvent::Failed {
                    error: message.clone(),
                })
                .await;
            finish_state(&state, JobStatus::Failed, None, Some(message));
        }
    }
    ctx.retire(&job_id);
    drop(internal_tx);
    let _ = event_forwarder.await;
}

async fn acquire_worker_lock_for_job(
    store: &Store,
    timeout: Duration,
    cancel: &CancellationToken,
) -> crate::error::Result<Option<crate::store::WorkerLock>> {
    let started = Instant::now();
    loop {
        if cancel.is_cancelled() {
            return Ok(None);
        }
        if let Some(lock) = store.try_acquire_worker_lock_once(HolderKind::Library)? {
            return Ok(Some(lock));
        }
        if started.elapsed() >= timeout {
            let holder = store
                .current_worker_lock()?
                .map(|meta| meta.holder_identity())
                .unwrap_or_default();
            return Err(crate::error::LlmusageError::LockBusy { holder });
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
}

fn update_state_from_event(state: &Arc<Mutex<JobState>>, event: &SyncEvent) {
    if let Ok(mut state) = state.lock() {
        state.snapshot.last_event = Some(event.clone());
    }
}

fn finish_state(
    state: &Arc<Mutex<JobState>>,
    status: JobStatus,
    summary: Option<String>,
    error: Option<String>,
) {
    if let Ok(mut state) = state.lock() {
        state.snapshot.status = status;
        state.snapshot.summary = summary;
        state.snapshot.error = error;
        state.snapshot.finished_at = Some(crate::util::now_utc());
    }
}

fn summary_text(summary: &SyncSummary) -> String {
    format!(
        "sources={} seen={} inserted_delta={} stored_events={}",
        summary.sources.len(),
        summary.total_seen,
        summary.total_inserted,
        summary.stored_events
    )
}

/// Records a terminal job in the bounded deque and evicts the oldest entries
/// that exceed `MAX_TERMINAL_JOBS`. O(1) amortized — one push, at most one pop
/// and one DashMap remove per call.
fn note_terminal_job(
    job_id: &JobId,
    inner: &Arc<DashMap<JobId, Arc<Mutex<JobState>>>>,
    terminal_order: &Arc<Mutex<VecDeque<JobId>>>,
) {
    let Ok(mut order) = terminal_order.lock() else {
        return;
    };
    order.push_back(job_id.clone());
    while order.len() > MAX_TERMINAL_JOBS {
        if let Some(evicted) = order.pop_front() {
            inner.remove(&evicted);
        }
    }
}

fn new_job_id() -> JobId {
    static NEXT: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(1);
    let sequence = NEXT.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
    format!("job-{sequence}")
}

#[allow(dead_code)]
fn _keep_sync_summary_public_contract(_: Option<SyncSummary>) {}

#[cfg(test)]
mod tests {
    use anyhow::Context as _;

    use super::*;
    use crate::paths::AppPaths;
    use tempfile::TempDir;

    struct FencedAssertionExecutor;

    impl crate::sync::executor::SyncExecutor for FencedAssertionExecutor {
        fn run_once<'a>(
            &'a self,
            _app: &'a AppContext,
            store: &'a Store,
            _lock_wait_ms: u64,
            _options: &'a SyncRunOptions,
            _sender: Option<&'a mut mpsc::Sender<SyncEvent>>,
            _cancel: &'a CancellationToken,
        ) -> crate::sync::executor::BoxFuture<'a, anyhow::Result<SyncSummary>> {
            Box::pin(async move {
                store
                    .write_permit()
                    .map_err(anyhow::Error::new)
                    .context("JobRegistry executor received an unfenced Store")?;
                Ok(SyncSummary {
                    sources: Vec::new(),
                    total_seen: 0,
                    total_inserted: 0,
                    stored_events: 0,
                })
            })
        }
    }

    #[tokio::test]
    async fn executor_receives_store_fenced_by_acquired_generation() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let paths = AppPaths::with_root(temp.path().to_path_buf())?;
        let store = Store::new(&paths)?;
        let registry = JobRegistry::new(Arc::new(FencedAssertionExecutor));

        let (job_id, _rx) = registry.start(&store, SyncOptions::default());
        let completed = wait_for_status(
            &registry,
            &job_id,
            JobStatus::Completed,
            Duration::from_secs(2),
        )
        .await?;
        assert!(completed.error.is_none());
        Ok(())
    }

    #[tokio::test]
    async fn start_returns_running_snapshot() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let paths = AppPaths::with_root(temp.path().to_path_buf())?;
        let store = Store::new(&paths)?;
        let registry = JobRegistry::default();

        let (job_id, rx) = registry.start(&store, SyncOptions::default());
        let snapshot = registry
            .snapshot(&job_id)
            .expect("job snapshot should exist");

        assert_eq!(snapshot.job_id, job_id);
        assert_eq!(snapshot.status, JobStatus::Running);
        drop(rx);
        Ok(())
    }

    #[tokio::test]
    async fn start_rejects_extra_jobs_instead_of_spawning_lock_waiters() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let paths = AppPaths::with_root(temp.path().to_path_buf())?;
        let store = Store::new(&paths)?;
        store.bootstrap()?;
        let blocker =
            store.acquire_worker_lock_with(Duration::from_secs(0), HolderKind::Library)?;
        let registry = JobRegistry::default();

        let (active_job_id, mut active_rx) = registry.try_start(
            &store,
            SyncOptions {
                source: Some("antigravity".to_string()),
                ..Default::default()
            },
        )?;
        wait_for_lock_waiting(&mut active_rx).await?;

        let rejected = registry
            .try_start(
                &store,
                SyncOptions {
                    source: Some("antigravity".to_string()),
                    ..Default::default()
                },
            )
            .expect_err("second active job should be rejected");
        assert_eq!(rejected.active_job_id, active_job_id);

        for _ in 0..8 {
            let (rejected_id, rejected_rx) = registry.start(
                &store,
                SyncOptions {
                    source: Some("antigravity".to_string()),
                    ..Default::default()
                },
            );
            drop(rejected_rx);
            let rejected_snapshot = registry
                .snapshot(&rejected_id)
                .expect("rejected snapshot should be retained");
            assert_eq!(rejected_snapshot.status, JobStatus::Failed);
            assert!(
                rejected_snapshot
                    .error
                    .as_deref()
                    .is_some_and(|error| error.contains(&active_job_id))
            );
        }

        let active_count = registry
            .list_recent(100)
            .into_iter()
            .filter(|snapshot| snapshot.status.is_active())
            .count();
        assert_eq!(active_count, 1, "only one job should remain active");

        assert!(registry.cancel(&active_job_id));
        drop(blocker);
        wait_for_status(
            &registry,
            &active_job_id,
            JobStatus::Cancelled,
            Duration::from_secs(2),
        )
        .await?;
        Ok(())
    }

    #[tokio::test]
    async fn lock_wait_cancel_finishes_without_later_running_sync() -> anyhow::Result<()> {
        let temp = TempDir::new()?;
        let paths = AppPaths::with_root(temp.path().to_path_buf())?;
        let store = Store::new(&paths)?;
        store.bootstrap()?;
        let blocker =
            store.acquire_worker_lock_with(Duration::from_secs(0), HolderKind::Library)?;
        let registry = JobRegistry::default();

        let (job_id, mut rx) = registry.try_start(
            &store,
            SyncOptions {
                source: Some("antigravity".to_string()),
                ..Default::default()
            },
        )?;
        wait_for_lock_waiting(&mut rx).await?;

        let started = Instant::now();
        assert!(registry.cancel(&job_id));
        let requested = registry.snapshot(&job_id).expect("job snapshot");
        assert_eq!(requested.status, JobStatus::Cancelling);
        assert_eq!(requested.summary.as_deref(), Some("cancellation requested"));
        assert!(requested.finished_at.is_none());

        drop(blocker);
        let cancelled = wait_for_status(
            &registry,
            &job_id,
            JobStatus::Cancelled,
            Duration::from_millis(1500),
        )
        .await?;
        assert!(
            started.elapsed() < Duration::from_millis(1500),
            "lock-wait cancellation should finish within SLA"
        );
        assert!(matches!(cancelled.last_event, Some(SyncEvent::Cancelled)));
        tokio::time::sleep(Duration::from_millis(150)).await;
        assert_eq!(
            registry.snapshot(&job_id).expect("job snapshot").status,
            JobStatus::Cancelled,
            "cancelled lock-wait jobs must not later acquire the lock and complete"
        );
        assert_eq!(count_rows(&store, "source_sync_status")?, 0);
        Ok(())
    }

    #[test]
    fn sync_options_accepts_parallelism_without_breaking_source_json() -> anyhow::Result<()> {
        let options: SyncOptions = serde_json::from_str(
            r#"{"source":"codex","recent_days":7,"parallelism":2,"rebuild":false}"#,
        )?;
        assert_eq!(options.source.as_deref(), Some("codex"));
        assert_eq!(options.recent_days, Some(7));
        assert_eq!(options.parallelism, Some(2));

        let payload = serde_json::to_value(&options)?;
        assert_eq!(payload["source"], "codex");
        assert_eq!(payload["parallelism"], 2);
        Ok(())
    }

    async fn wait_for_lock_waiting(rx: &mut mpsc::Receiver<JobEvent>) -> anyhow::Result<()> {
        let found = tokio::time::timeout(Duration::from_secs(2), async {
            while let Some(event) = rx.recv().await {
                if matches!(event, SyncEvent::LockWaiting { .. }) {
                    return true;
                }
            }
            false
        })
        .await?;
        anyhow::ensure!(found, "job did not enter lock waiting state");
        Ok(())
    }

    async fn wait_for_status(
        registry: &JobRegistry,
        job_id: &str,
        expected: JobStatus,
        timeout: Duration,
    ) -> anyhow::Result<JobSnapshot> {
        let started = Instant::now();
        loop {
            let snapshot = registry
                .snapshot(job_id)
                .ok_or_else(|| anyhow::anyhow!("missing job snapshot: {job_id}"))?;
            if snapshot.status == expected {
                return Ok(snapshot);
            }
            if started.elapsed() >= timeout {
                anyhow::bail!(
                    "job {job_id} did not reach {expected:?}; last status {:?}",
                    snapshot.status
                );
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
    }

    #[test]
    fn rejected_jobs_are_bounded_at_max_terminal_jobs() {
        let registry = JobRegistry::default();
        // inject MAX_TERMINAL_JOBS + 50 rejected snapshots directly
        let total = MAX_TERMINAL_JOBS + 50;
        let mut ids = Vec::with_capacity(total);
        for i in 0..total {
            let job_id = format!("test-job-{i}");
            let now = crate::util::now_utc();
            let state = JobState {
                snapshot: JobSnapshot {
                    job_id: job_id.clone(),
                    status: JobStatus::Failed,
                    summary: None,
                    last_event: None,
                    error: Some("rejected".to_string()),
                    started_at: now.clone(),
                    finished_at: Some(now),
                },
                cancel: CancellationToken::new(),
            };
            registry
                .inner
                .insert(job_id.clone(), Arc::new(Mutex::new(state)));
            note_terminal_job(&job_id, &registry.inner, &registry.terminal_order);
            ids.push(job_id);
        }
        assert!(
            registry.inner.len() <= MAX_TERMINAL_JOBS,
            "registry should be bounded at {MAX_TERMINAL_JOBS}, got {}",
            registry.inner.len()
        );
        // most recent jobs must still be queryable
        for id in ids.iter().rev().take(MAX_TERMINAL_JOBS) {
            assert!(
                registry.snapshot(id).is_some(),
                "recent job {id} should still be in registry"
            );
        }
    }

    fn count_rows(store: &Store, table: &str) -> anyhow::Result<i64> {
        let conn = store.open_connection()?;
        let sql = format!("SELECT COUNT(*) FROM {table}");
        Ok(conn.query_row(&sql, [], |row| row.get(0))?)
    }
}
